_wandb:
    value:
        cli_version: 0.22.2
        e:
            f8oslduwglp3j2aitzqsn33tmuwv9tkl:
                codePath: notebooks\05_model_training.ipynb
                codePathLocal: 05_model_training.ipynb
                email: dawtdart615@gmail.com
                executable: c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: 86e79cbe94e8a3f93d3d5f59d027f0bcb1f35714
                    remote: https://github.com/Duongvu05/Hanoi-Temperature-Forecasting.git
                host: ANTAM-HOME
                os: Windows-10-10.0.19045-SP0
                program: f:\PYTHON\prepare Data and Visualisation\Hanoi-Temperature-Forecasting\notebooks\05_model_training.ipynb
                python: CPython 3.12.6
                root: f:\PYTHON\prepare Data and Visualisation\Hanoi-Temperature-Forecasting\notebooks
                startedAt: "2025-10-21T09:52:30.665596Z"
                writerId: f8oslduwglp3j2aitzqsn33tmuwv9tkl
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.6
            "5": 0.22.2
            "8":
                - 1
                - 3
            "12": 0.22.2
            "13": windows-amd64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
