_wandb:
    value:
        cli_version: 0.22.2
        e:
            f60z2ypzblbn0tx3i6brtfu1gd9nq49k:
                codePath: notebooks\05_model_training.ipynb
                codePathLocal: 05_model_training.ipynb
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "262142947328"
                        used: "132811382784"
                email: dawtdart615@gmail.com
                executable: c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: 86e79cbe94e8a3f93d3d5f59d027f0bcb1f35714
                    remote: https://github.com/Duongvu05/Hanoi-Temperature-Forecasting.git
                host: ANTAM-HOME
                memory:
                    total: "16939200512"
                os: Windows-10-10.0.19045-SP0
                program: f:\PYTHON\prepare Data and Visualisation\Hanoi-Temperature-Forecasting\notebooks\05_model_training.ipynb
                python: CPython 3.12.6
                root: f:\PYTHON\prepare Data and Visualisation\Hanoi-Temperature-Forecasting\notebooks
                startedAt: "2025-10-21T09:53:25.507120Z"
                writerId: f60z2ypzblbn0tx3i6brtfu1gd9nq49k
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.6
            "5": 0.22.2
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.22.2
            "13": windows-amd64
model:
    value:
        - preprocessor
        - var_thresh
        - rf
random_state:
    value: 42
